// Bakes the worker and the compiler into TypeScript string constants.
//
// The worker has to reach the browser as text, because it is started from a
// blob rather than a URL. Doing that here rather than with a bundler feature
// keeps the output identical whether a host bundles this package or serves it
// as files.

import { buildSync } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../src');
const out = resolve(src, 'generated');

const read = (p) => readFileSync(p, 'utf8');

// Bundled rather than concatenated, so the worker can be an ordinary module
// that imports what it uses and is typechecked like everything else. What comes
// out is one script with the imports resolved away, which is what a blob needs.
const bundled = buildSync({
  entryPoints: [resolve(src, 'runtime/worker-body.ts')],
  bundle: true,
  format: 'iife',
  target: 'es2022',
  write: false,
});
const worker = bundled.outputFiles[0].text;

if (/^\s*(import|export)\s/m.test(worker)) {
  throw new Error(
    'the worker source still has module syntax in it, so it could not run from a blob',
  );
}

// The lean compiler. The span-aware variant beside it annotates its output
// with source positions; the editor resolves names by scope instead
// (symbols.ts) and has no use for them, so it does not pay for them — a host
// that wants positions passes compile_to_dag_with_spans via `compiler`.
const compiler = read(resolve(here, '../../compiler/compile_to_dag.dag'));

mkdirSync(out, { recursive: true });
writeFileSync(
  resolve(out, 'worker-source.ts'),
  `// Generated by scripts/generate.mjs. Not checked in.\n` +
    `export const workerSource = ${JSON.stringify(worker)};\n`,
);
writeFileSync(
  resolve(out, 'compiler.ts'),
  `// Generated by scripts/generate.mjs from compiler/compile_to_dag.dag. Not checked in.\n` +
    `export const defaultCompiler = ${JSON.stringify(compiler)};\n`,
);

const kb = (s) => `${(s.length / 1024).toFixed(1)} kB`;
console.log(`worker source ${kb(worker)}, compiler ${kb(compiler)}`);
